upload_file:
  path: /upload
  defaults: { _controller: AppBundle:ConverterApi:upload }
  methods:  [POST]

status:
  path: /status/{uid}
  defaults: { _controller: AppBundle:ConverterApi:getStatus }
  methods:  [GET]

download:
  path: /download/{fileName}
  defaults: { _controller: AppBundle:ConverterApi:getConvertedFile }
  methods:  [GET]
